---
title: "R Notebook"
output: html_notebook
---
```{r}
#Steps to this model:
#1) First fit log-logistic curves to each tdt curve (each temperature) for the data supplied
#2) Then fit a linear model to both log-logistic shape and scale vs temp
#3) Next, we deal with the fluctuating temp data:
#     start cumulative survival (S(t)) at 1 (S(t_0)=1)
#     for each timestep t_i:
#         Find the log-logistic shape and scale parameters corresponding to the temperature T_i at timestep t_i. These parameters give a cumulative survival function of time (time spent under the constant temperature used to make the LLogis TDT curve, which we will call t*. Not the fluctuating temperature t_i). This distribution has CDF F_w(t*), PDF f_w(t*), cumulative survival S_w(t*)=1-F_w(t*)
#         Find chance of surviving from time t_i-1 to t_i: 
#             i) First, we find: S_w^-1(S(t_i-1))=t*_i
#             ii) Calculate failure in that time interval f.rate_i=S(t_i)/S(t_i-1)
#             iii) Calculate cumulative mortality between t_i-1 and t_i as (t_i-(t_i-1))*f.rate_i
#             iiii)Let S_i=(S_i-1)-[(t_i-(t_i-1))*f_w(t*_i)]
#Note that this loop assumes the temperature is constant at T_i for the time interval from t_i-1 to t_i. You could alternatively take the max or average of the temperatures at these time points. 
#replace with shape="constant" if you want the model to assume constant shape
llogis.mod = function(TDT.dat,temp.dat,shape="linear"){
  #step 1
shape.vec = c()
shape.vec.var = c()
scale.vec = c()
scale.vec.var = c()
for (j in unique(TDT.dat$Tref)){
mod.j = flexsurvreg(Surv(time,event) ~ 1, data = TDT.dat[(TDT.dat$Tref==j),], dist=
                               "llogis")
shape.vec.var = c(shape.vec.var, mod.j$cov[[1,1]])
scale.vec.var = c(scale.vec.var, exp(mod.j$cov[[2,2]]))
shape.vec = c(shape.vec,mod.j$coefficients[[1]])
#exponentiate because the function flexsurvreg automatically puts scale on a log scale
scale.vec = c(scale.vec,exp(mod.j$coefficients[[2]]))
}

#step 2
shape.lm=lm(shape.vec~unique(TDT.dat$Tref))
shape.slope=lm(shape.vec~unique(TDT.dat$Tref))$coefficients[[2]]
shape.int=lm(shape.vec~unique(TDT.dat$Tref))$coefficients[[1]]
#constant shape lm
cons.shape.lm=lm(shape.vec~1)
cons.shape.int=cons.shape.lm$coefficients[[1]]
#note the log transformation
scale.lm=lm(log10(scale.vec)~unique(TDT.dat$Tref))
scale.slope=scale.lm$coefficients[[2]]
scale.int=scale.lm$coefficients[[1]]

shape.pars=c(shape.slope,shape.int,cons.shape.int)
logscale.pars=c(scale.slope,scale.int)

#predict under fluctuating temperatures with shape as a linear function of temperature
if (shape=="linear"){
#step 3
cum.surv = rep(NA,nrow(temp.dat))
cum.surv[1]=1
fail.rates = rep(0,nrow(temp.dat))
mean.list=c()
shape.list=c()
log.list=c()

for (i in 2:nrow(temp.dat)){
  T_i=temp.dat$Temperature[i]
  T_prev=temp.dat$Temperature[i-1]
  t_i=temp.dat$Time_min[i]
  t_prev=temp.dat$Time_min[i-1]
  t_diff=t_i-t_prev
  #untransform from log scale
  scale_i = 10^(scale.slope*mean(T_i,T_prev)+scale.int)
  shape_i = shape.slope*mean(T_i,T_prev)+shape.int
  mean.list=c(mean.list,((pi*scale_i)/shape_i)/(sin(pi/shape_i)))
  log.list=c(log.list,cum.surv[i-1])
  #inverse CDF
  prob = 1-cum.surv[i-1]
  t_star_i=scale_i*(prob/(1-prob))^(1/shape_i)
  #llogis pdf/failure rate
  #Get the proportion that made it th timestep i/prop that made it to i-1 to get the prop that died in the meantime
  fail.rates[i]=(1-pllogis(t_star_i,shape_i,scale_i))-(1-pllogis(t_star_i+t_diff,shape_i,scale_i))
  cum.surv[i]=cum.surv[i-1]-fail.rates[i]
}
med.tdt=temp.dat$Time_min[which.max(cum.surv<0.5)]
cum.surv.post=na.omit(cum.surv)
times.post=temp.dat$Time_min[1:length(cum.surv.post)]
expected.tdt=mean(-sum((cum.surv.post[2:length(cum.surv.post)]-cum.surv.post[1:(length(cum.surv.post)-1)])*times.post[2:length(cum.surv.post)]), -sum((cum.surv.post[2:length(cum.surv.post)]-cum.surv.post[1:(length(cum.surv.post)-1)])*times.post[1:(length(cum.surv.post)-1)]))
}

if (shape=="constant"){
 #step 3
cum.surv = rep(NA,nrow(temp.dat))
cum.surv[1]=1
fail.rates = rep(0,nrow(temp.dat))
mean.list=c()
shape.list=c()
log.list=c()

for (i in 2:nrow(temp.dat)){
  T_i=temp.dat$Temperature[i]
  T_prev=temp.dat$Temperature[i-1]
  t_i=temp.dat$Time_min[i]
  t_prev=temp.dat$Time_min[i-1]
  t_diff=t_i-t_prev
  #untransform from log scale
  scale_i = 10^(scale.slope*mean(T_i,T_prev)+scale.int)
  #this is the only line that is different
  shape_i = cons.shape.int
  mean.list=c(mean.list,((pi*scale_i)/shape_i)/(sin(pi/shape_i)))
  log.list=c(log.list,cum.surv[i-1])
  #inverse CDF
  prob = 1-cum.surv[i-1]
  t_star_i=scale_i*(prob/(1-prob))^(1/shape_i)
  #llogis pdf/failure rate
  #Get the proportion that made it th timestep i/prop that made it to i-1 to get the prop that died in the meantime
  fail.rates[i]=(1-pllogis(t_star_i,shape_i,scale_i))-(1-pllogis(t_star_i+t_diff,shape_i,scale_i))
  cum.surv[i]=cum.surv[i-1]-fail.rates[i]
}
med.tdt=temp.dat$Time_min[which.max(cum.surv<0.5)]
cum.surv.post=na.omit(cum.surv)
times.post=temp.dat$Time_min[1:length(cum.surv.post)]
expected.tdt=mean(-sum((cum.surv.post[2:length(cum.surv.post)]-cum.surv.post[1:(length(cum.surv.post)-1)])*times.post[2:length(cum.surv.post)]), -sum((cum.surv.post[2:length(cum.surv.post)]-cum.surv.post[1:(length(cum.surv.post)-1)])*times.post[1:(length(cum.surv.post)-1)])) 
  
  
  
}

output=list(med.tdt,expected.tdt,cum.surv.post,shape.pars,logscale.pars)
names(output)=c("med.tdt","expected.tdt","cum.surv","shape.pars","logscale.pars")
return(output)
}
```

```{r}
#Steps to this model:
#1) First fit weibull curves to each tdt curve (each temperature) for the data supplied
#2) Then fit a linear model to both weibull shape and scale vs temp
#3) Next, we deal with the fluctuating temp data:
#     start cumulative survival (S(t)) at 1 (S(t_0)=1)
#     for each timestep t_i:
#         Find the weibull shape and scale parameters corresponding to the temperature T_i at timestep t_i. These parameters give a cumulative survival function of time (time spent under the constant temperature used to make the Weibull TDT curve, which we will call t*. Not the fluctuating temperature t_i). This distribution has CDF F_w(t*), PDF f_w(t*), cumulative survival S_w(t*)=1-F_w(t*)
#         Find chance of surviving from time t_i-1 to t_i: 
#             i) First, we find: S_w^-1(S(t_i-1))=t*_i
#             ii) Calculate failure in that time interval f.rate_i=S(t_i)/S(t_i-1)
#             iii) Calculate cumulative mortality between t_i-1 and t_i as (t_i-(t_i-1))*f.rate_i
#             iiii)Let S_i=(S_i-1)-[(t_i-(t_i-1))*f_w(t*_i)]
#Note that this loop assumes the temperature is constant at T_i for the time interval from t_i-1 to t_i. You could alternatively take the max or average of the temperatures at these time points. 
#replace with shape="constant" if you want the model to assume constant shape
weibull.mod = function(TDT.dat,temp.dat,shape="linear"){
  #step 1
shape.vec = c()
shape.vec.var = c()
scale.vec = c()
scale.vec.var = c()
for (j in unique(TDT.dat$Tref)){
mod.j = flexsurvreg(Surv(time,event) ~ 1, data = TDT.dat[(TDT.dat$Tref==j),], dist=
                               "weibull")
shape.vec.var = c(shape.vec.var, mod.j$cov[[1,1]])
scale.vec.var = c(scale.vec.var, exp(mod.j$cov[[2,2]]))
shape.vec = c(shape.vec,mod.j$coefficients[[1]])
#exponentiate because the function flexsurvreg automatically puts scale on a log scale
scale.vec = c(scale.vec,exp(mod.j$coefficients[[2]]))
}

#step 2
shape.lm=lm(shape.vec~unique(TDT.dat$Tref))
shape.slope=lm(shape.vec~unique(TDT.dat$Tref))$coefficients[[2]]
shape.int=lm(shape.vec~unique(TDT.dat$Tref))$coefficients[[1]]
#constant shape lm
cons.shape.lm=lm(shape.vec~1)
cons.shape.int=cons.shape.lm$coefficients[[1]]
#note the log transformation
scale.lm=lm(log10(scale.vec)~unique(TDT.dat$Tref))
scale.slope=scale.lm$coefficients[[2]]
scale.int=scale.lm$coefficients[[1]]

shape.pars=c(shape.slope,shape.int,cons.shape.int)
logscale.pars=c(scale.slope,scale.int)

#predict under fluctuating temperatures with shape as a linear function of temperature
if (shape=="linear"){
#step 3
cum.surv = rep(NA,nrow(temp.dat))
cum.surv[1]=1
fail.rates = rep(0,nrow(temp.dat))
mean.list=c()
shape.list=c()
log.list=c()

for (i in 2:nrow(temp.dat)){
  T_i=temp.dat$Temperature[i]
  T_prev=temp.dat$Temperature[i-1]
  t_i=temp.dat$Time_min[i]
  t_prev=temp.dat$Time_min[i-1]
  t_diff=t_i-t_prev
  #untransform from log scale
  scale_i = 10^(scale.slope*mean(T_i,T_prev)+scale.int)
  shape_i = shape.slope*mean(T_i,T_prev)+shape.int
  mean.list=c(mean.list,scale_i*gamma(1+1/shape_i))
  log.list=c(log.list,cum.surv[i-1])
  #inverse CDF
  t_star_i=scale_i*(-log(cum.surv[i-1]))^(1/shape_i)
  #weibull pdf/failure rate
  #Get the proportion that made it th timestep i/prop that made it to i-1 to get the prop that died in the meantime
  fail.rates[i]=(1-pweibull(t_star_i,shape_i,scale_i))-(1-pweibull(t_star_i+t_diff,shape_i,scale_i))
  cum.surv[i]=cum.surv[i-1]-fail.rates[i]
}
med.tdt=temp.dat$Time_min[which.max(cum.surv<0.5)]
cum.surv.post=na.omit(cum.surv)
times.post=temp.dat$Time_min[1:length(cum.surv.post)]
expected.tdt=mean(-sum((cum.surv.post[2:length(cum.surv.post)]-cum.surv.post[1:(length(cum.surv.post)-1)])*times.post[2:length(cum.surv.post)]), -sum((cum.surv.post[2:length(cum.surv.post)]-cum.surv.post[1:(length(cum.surv.post)-1)])*times.post[1:(length(cum.surv.post)-1)]))
}

if (shape=="constant"){
 #step 3
cum.surv = rep(NA,nrow(temp.dat))
cum.surv[1]=1
fail.rates = rep(0,nrow(temp.dat))
mean.list=c()
shape.list=c()
log.list=c()

for (i in 2:nrow(temp.dat)){
  T_i=temp.dat$Temperature[i]
  T_prev=temp.dat$Temperature[i-1]
  t_i=temp.dat$Time_min[i]
  t_prev=temp.dat$Time_min[i-1]
  t_diff=t_i-t_prev
  #untransform from log scale
  scale_i = 10^(scale.slope*mean(T_i,T_prev)+scale.int)
  #this is the only line that is different
  shape_i = cons.shape.int
  mean.list=c(mean.list,scale_i*gamma(1+1/shape_i))
  log.list=c(log.list,cum.surv[i-1])
  #inverse CDF
  t_star_i=scale_i*(-log(cum.surv[i-1]))^(1/shape_i)
  #weibull pdf/failure rate
  #Get the proportion that made it th timestep i/prop that made it to i-1 to get the prop that died in the meantime
  fail.rates[i]=(1-pweibull(t_star_i,shape_i,scale_i))-(1-pweibull(t_star_i+t_diff,shape_i,scale_i))
  cum.surv[i]=cum.surv[i-1]-fail.rates[i]
}
med.tdt=temp.dat$Time_min[which.max(cum.surv<0.5)]
cum.surv.post=na.omit(cum.surv)
times.post=temp.dat$Time_min[1:length(cum.surv.post)]
expected.tdt=mean(-sum((cum.surv.post[2:length(cum.surv.post)]-cum.surv.post[1:(length(cum.surv.post)-1)])*times.post[2:length(cum.surv.post)]), -sum((cum.surv.post[2:length(cum.surv.post)]-cum.surv.post[1:(length(cum.surv.post)-1)])*times.post[1:(length(cum.surv.post)-1)])) 
  
  
  
}

output=list(med.tdt,expected.tdt,cum.surv.post,shape.pars,logscale.pars)
names(output)=c("med.tdt","expected.tdt","cum.surv","shape.pars","logscale.pars")
return(output)
}
```